spring:
  application:
    name: library-events-producer
  profiles:
    active: local
  kafka:
    producer:
#      bootstrap-servers: localhost:9092
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.add.type.headers: false
    admin:
      properties:
        bootstrap-servers: kafka:9092
